services:
  mongo:
    image: mongo:7
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  node-app:
    build: ./node-app
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_URL=mongodb://mongo:27017/ujian_db

volumes:
  mongo-data:
